services:
    kernel.listener.pre_soft_delete_listener:
        class: AppBundle\EventListener\PreSoftDeleteableListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postSoftDelete }
